# Generated by Django 6.0 on 2025-12-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('supplements', 'Supplements'), ('skincare', 'Skincare'), ('weight', 'Weight Management'), ('energy', 'Energy & Vitality')], max_length=100),
        ),
    ]
