# Generated by Django 6.0 on 2026-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Drinks', 'Drinks'), ('Bee Products', 'Bee Products'), ('Combo Packs', 'Combo Packs'), ('Nutritional Supplements', 'Nutritional Supplements')], max_length=100),
        ),
    ]
