# Generated by Django 6.0 on 2026-01-20 18:51

import Products.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[Products.models.validate_image_size], verbose_name='image'),
        ),
    ]
