# Generated by Django 6.0 on 2026-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Nutrition', 'Nutrition'), ('Fitness', 'Fitness'), ('Mental Health', 'Mental Health'), ('Wellness Tips', 'Wellness Tips'), ('Lifestyle', 'Lifestyle')], max_length=100),
        ),
    ]
