# Generated by Django 6.0 on 2026-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Weight Loss & Detox', 'Weight Loss & Detox'), ('Skin Care & Beauty', 'Skin Care & Beauty'), ('Digestive Health & Gut Wellness', 'Digestive Health & Gut Wellness'), ('Energy, Fitness & Performance', 'Energy, Fitness & Performance'), ('Health & Wellness Education', 'Health & Wellness Education'), ('Customer Stories & Results', 'Customer Stories & Results'), ('Forever Living Business & Lifestyle', 'Forever Living Business & Lifestyle'), ('Buying Guides & FAQs', 'Buying Guides & FAQs')], max_length=100),
        ),
    ]
