# Generated by Django 6.0 on 2026-01-20 18:51

import Blog.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[Blog.models.validate_image_size], verbose_name='image'),
        ),
    ]
